version: 2

sources:
  - name: raw_assets
    schema: main
    tables:
      - name: raw_storage_provider_daily_power
        meta:
          dagster:
            asset_key: ["raw_storage_provider_daily_power"]
      - name: raw_datacapstats_verified_clients
        meta:
          dagster:
            asset_key: ["raw_datacapstats_verified_clients"]
      - name: raw_filecoin_state_market_deals
        meta:
          dagster:
            asset_key: ["raw_filecoin_state_market_deals"]
      - name: raw_storage_providers_location_provider_quest
        meta:
          dagster:
            asset_key: ["raw_storage_providers_location_provider_quest"]
