[project]
name = "fdp"
version = "1.0.0"
authors = [{ name = "David Gasquez" }]
dependencies = [
    "altair>=5.5.0",
    "carbox>=0.3",
    "dag-json>=0.3",
    "dagster>=1.9.3",
    "dagster-dbt>=0.25.3",
    "dagster-duckdb-pandas>=0.25.3",
    "dagster-gcp>=0.25.3",
    "dbt-core>=1.8.8",
    "dbt-duckdb>=1.9.1",
    "duckdb>=1.1.3",
    "google-cloud-bigquery-storage>=2.27.0",
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "pandas>=2.2.3",
    "polars>=1.19.0",
    "pyarrow>=18.1.0",
    "web3>=7.6.1",
]
requires-python = ">=3.10, <3.13"
readme = "README.md"
license = { text = "MIT" }

[dependency-groups]
dev = [
    "dagster-webserver>=1.9.6",
    "ipykernel>=6.29.5",
]

[project.urls]
Homepage = "https://filecoindataportal.xyz/"
Changelog = "https://github.com/davidgasquez/filecoin-data-portal/commits/main/"
Issues = "https://github.com/davidgasquez/filecoin-data-portal/issues"
CI = "https://github.com/davidgasquez/filecoin-data-portal/actions"

[tool.setuptools]
packages = ["fdp"]

[tool.dagster]
module_name = "fdp.definitions"
code_location_name = "fdp"
