[project]
name = "fdp"
version = "0.1.0"
authors = [{ name = "David Gasquez" }]
dependencies = [
    "altair",
    "dagster-dbt",
    "dagster-duckdb-pandas",
    "dagster==1.7.10",
    "databricks-sql-connector",
    "dbt-core",
    "dbt-duckdb",
    "duckdb==1.0.0",
    "ijson",
    "ipykernel",
    "ipywidgets",
    "httpx",
    "jupysql",
    "jupyterlab",
    "matplotlib",
    "nbformat",
    "pandas",
    "pyarrow",
    "pymongo",
    "regex",
    "toml",
    "tqdm",
    "zstandard",
]
requires-python = ">=3.10, <3.12"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
Homepage = "https://filecoin-data-portal.on-fleek.app/"
Changelog = "https://github.com/davidgasquez/filecoin-data-portal/commits/main/"
Issues = "https://github.com/davidgasquez/filecoin-data-portal/issues"
CI = "https://github.com/davidgasquez/filecoin-data-portal/actions"

[project.optional-dependencies]
dev = ["dagster-webserver", "ruff"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"datadex" = ["../dbt/**"]

[tool.setuptools]
packages = ["fdp"]

[tool.dagster]
module_name = "fdp"

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
length-sort = true
