project:
  type: website
  output-dir: .quarto/_site
  preview:
    port: 4200

website:
  title: "Filecoin Data Portal"
  favicon: "favicon.ico"
  repo-url: https://github.com/davidgasquez/filecoin-data-portal
  repo-actions: [edit, issue]
  search: false
  navbar:
    logo: favicon.ico
    pinned: false
    left:
      - text: "Data"
        href: https://ipfs.io/ipns/k51qzi5uqu5dh0eqsyw9shepsspstaduq8lgnept49epxvo4t8qfi6ridcmt8k
      - text: "Docs"
        href: docs/data-sources.html
    right:
      - text: "New Request"
        href: https://github.com/davidgasquez/filecoin-data-portal/issues/new
    tools:
      - icon: twitter
        href: https://twitter.com/davidgasquez/
      - icon: github
        href: https://github.com/davidgasquez/filecoin-data-portal

format:
  html:
    theme: cosmo
    toc: true
    echo: false
