project:
  type: website
  output-dir: .quarto/_site
  preview:
    port: 4200

website:
  title: "Filecoin Data Portal"
  favicon: "favicon.ico"
  repo-url: https://github.com/davidgasquez/filecoin-data-portal
  repo-actions: [edit, issue]
  search: false
  page-footer:
    center: "David Gasquez"
  navbar:
    logo: "https://www.pngall.com/wp-content/uploads/10/Filecoin-Crypto-Logo-180x180.png"
    search: false
    pinned: true
    left:
      - text: "Docs"
        href: docs/data-sources.html
    tools:
      - icon: twitter
        href: https://twitter.com/davidgasquez/
      - icon: github
        href: https://github.com/davidgasquez/filecoin-data-portal

format:
  html:
    theme: simplex
    code-fold: true
    toc: true
    echo: false
