name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      SPACESCOPE_TOKEN: ${{ secrets.SPACESCOPE_TOKEN }}
      DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      motherduck_token: ${{ secrets.motherduck_token }}
      DATABRICKS_SERVER_HOSTNAME: ${{ secrets.DATABRICKS_SERVER_HOSTNAME }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
      DATABRICKS_ACCESS_TOKEN: ${{ secrets.DATABRICKS_ACCESS_TOKEN }}
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      REPUTATION_MONGODB_URI: ${{ secrets.REPUTATION_MONGODB_URI }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENCODED_GOOGLE_APPLICATION_CREDENTIALS:  ${{ secrets.ENCODED_GOOGLE_APPLICATION_CREDENTIALS }}
      R2_ACCESS_KEY_ID : ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY : ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_ACCOUNT_ID : ${{ secrets.R2_ACCOUNT_ID }}
      R2_BUCKET : ${{ secrets.R2_BUCKET }}

    steps:
        - name: Free Disk Space
          uses: jlumbroso/free-disk-space@main
          with:
            tool-cache: true
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            docker-images: true
            swap-storage: true

        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.12
            cache: pip

        - name: Install dependencies
          run: pip install -e .

        - name: Run
          run: make run

        - name: Export Tables
          run: make tables

        - name: Install Quarto
          uses: quarto-dev/quarto-actions/setup@v2

        - name: Render
          run: make render

        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
              node-version: 20

        - name: Push to IPFS
          uses: filebase/ipfs-action@master
          id: ipfs
          with:
            path: portal/.quarto/_site
            service: filebase
            pinName: filecoin-data-portal-tables
            filebaseBucket: filecoin-data-portal
            filebaseKey: ${{ secrets.FILEBASE_KEY }}
            filebaseSecret: ${{ secrets.FILEBASE_SECRET }}
            key: filecoin-data-portal-db

        - name: Create CID file
          run: echo ${{ steps.ipfs.outputs.cid }} > data/IPFS_CID

        - name: Commit and Push
          run: |
            git config --global user.name "GitHub Action"
            git config --global user.email "actions@users.noreply.github.com"
            git config --global push.autoSetupRemote true
            git pull
            git add data/IPFS_CID
            if git diff-index --quiet HEAD --; then
              echo "No changes to commit"
            else
              git commit -m "chore: :id: Update CID"
              git push
            fi

        - name: Upload to R2
          uses: ryand56/r2-upload-action@latest
          with:
            r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
            r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
            r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
            r2-bucket: ${{ secrets.R2_BUCKET }}
            source-dir: data/tables/
            destination-dir: ./
