name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/davidgasquez/fdp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  run:
    name: Run
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/davidgasquez/fdp:latest
      volumes:
        - ./:/workspaces/filecoin-data-portal/
    # defaults:
    #   run:
    #     working-directory: /workspaces/filecoin-data-portal/
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run
          run: echo "Hello world"
        - name: PWD
          run: pwd
        - name: List files
          run: ls -la
        - name: Install packages
          run: pip install -e .
        - name: Run DAG
          run: make run
        - name: Render Quarto
          run: make render

      # - name: Build Docker
      #   run: docker build -t davidgasquez/fdp:latest . --build-arg SPACESCOPE_TOKEN=${{ secrets.SPACESCOPE_TOKEN }}

      # - name: Run DAG
      #   run: docker run -t -e SPACESCOPE_TOKEN=${{ secrets.SPACESCOPE_TOKEN }} -v $PWD/:/workspaces/filecoin-data-portal/ davidgasquez/fdp:latest make run

      # - name: Render Quarto
      #   run: docker run -t -e SPACESCOPE_TOKEN=${{ secrets.SPACESCOPE_TOKEN }} -v $PWD/:/workspaces/filecoin-data-portal/ davidgasquez/fdp:latest make render

      # - name: Publish Docs
      #   uses: JamesIves/github-pages-deploy-action@4.0.0
      #   with:
      #     branch: gh-pages
      #     folder: .portal/quarto/_site
